const connection = require('../connection');
const Sequelize = require('sequelize');
const Hero = require('./Hero');

module.exports = connection.define('hero_detail', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    hero_id: {
        type: Sequelize.INTEGER,
        references: {
            model: Hero,
            key: ''
        }
    },
    ms: Sequelize.INTEGER,
    as: Sequelize.INTEGER,
    turn_rate: Sequelize.FLOAT,
    vision_range_day: Sequelize.INTEGER,
    vision_range_night: Sequelize.INTEGER,
    attack_range: Sequelize.INTEGER,
    projectile_speed: Sequelize.STRING,
    attack_animation_point: Sequelize.FLOAT,
    attack_animation_backswing: Sequelize.FLOAT,
    base_attack_time: Sequelize.FLOAT,
    dmg_block: Sequelize.INTEGER,
    collision_size: Sequelize.INTEGER,
    legs: Sequelize.INTEGER,
    hp_lv_0: Sequelize.INTEGER,
    hp_lv_1: Sequelize.INTEGER,
    hp_lv_15: Sequelize.INTEGER,
    hp_lv_25: Sequelize.INTEGER,
    hp_lv_30: Sequelize.INTEGER,
    hp_reg_lv_0: Sequelize.INTEGER,
    hp_reg_lv_1: Sequelize.INTEGER,
    hp_reg_lv_15: Sequelize.INTEGER,
    hp_reg_lv_25: Sequelize.INTEGER,
    hp_reg_lv_30: Sequelize.INTEGER,
    magic_resist_lv_0: Sequelize.INTEGER,
    magic_resist_lv_1: Sequelize.INTEGER,
    magic_resist_lv_15: Sequelize.INTEGER,
    magic_resist_lv_25: Sequelize.INTEGER,
    magic_resist_lv_30: Sequelize.INTEGER,
    mp_lv_0: Sequelize.INTEGER,
    mp_lv_1: Sequelize.INTEGER,
    mp_lv_15: Sequelize.INTEGER,
    mp_lv_25: Sequelize.INTEGER,
    mp_lv_30: Sequelize.INTEGER,
    mp_reg_lv_0: Sequelize.INTEGER,
    mp_reg_lv_1: Sequelize.INTEGER,
    mp_reg_lv_15: Sequelize.INTEGER,
    mp_reg_lv_25: Sequelize.INTEGER,
    mp_reg_lv_30: Sequelize.INTEGER,
    spell_dmg_lv_0: Sequelize.INTEGER,
    spell_dmg_lv_1: Sequelize.INTEGER,
    spell_dmg_lv_15: Sequelize.INTEGER,
    spell_dmg_lv_25: Sequelize.INTEGER,
    spell_dmg_lv_30: Sequelize.INTEGER,
    armor_lv_0: Sequelize.INTEGER,
    armor_lv_1: Sequelize.INTEGER,
    armor_lv_15: Sequelize.INTEGER,
    armor_lv_25: Sequelize.INTEGER,
    armor_lv_30: Sequelize.INTEGER,
    atts_per_sec_lv_0: Sequelize.INTEGER,
    atts_per_sec_lv_1: Sequelize.INTEGER,
    atts_per_sec_lv_15: Sequelize.INTEGER,
    atts_per_sec_lv_25: Sequelize.INTEGER,
    atts_per_sec_lv_30: Sequelize.INTEGER,
    ms_amp_lv_0: Sequelize.INTEGER,
    ms_amp_lv_1: Sequelize.INTEGER,
    ms_amp_lv_15: Sequelize.INTEGER,
    ms_amp_lv_25: Sequelize.INTEGER,
    ms_amp_lv_30: Sequelize.INTEGER,
    dmg_lv_0_min: Sequelize.INTEGER,
    dmg_lv_0_max: Sequelize.INTEGER,
    dmg_lv_1_min: Sequelize.INTEGER,
    dmg_lv_1_max: Sequelize.INTEGER,
    dmg_lv_15_min: Sequelize.INTEGER,
    dmg_lv_15_max: Sequelize.INTEGER,
    dmg_lv_25_min: Sequelize.INTEGER,
    dmg_lv_25_max: Sequelize.INTEGER,
    dmg_lv_30_min: Sequelize.INTEGER,
    dmg_lv_30_max: Sequelize.INTEGER,
}, { timestamps: false, tableName: 'hero_details' });